name = "os"

[[Function]]
name = "modulo"
description = """`modulo(int a, int b) => int`<br>
Modulo returns the remainder of `a % b`. To use this function properly
make sure both values are integers.
"""
example = """
var rem = modulo(567, 89);
print rem; // 33
"""