name = "string"

[[Function]]
name = "char_at()"
description = """*char_at(string str, int index) => string*<br>
CharAt returns the character in a string at the specified index,
if this functions reaches an error, either the program will panic or return nil.
"""
example = """
var char = char_at("hello", 3);
print char; // l
"""

[[Function]]
name = "len()"
description = """*len(string) => int*<br>
Len returns the length of a string. If this function reaches an error it returns 0 alongside
an error message.
"""
example = """
var length = len("OOOOOOO");
print length; // 7
"""

